name: 自动爬取图片

on:
  schedule:
    # 每天凌晨3点运行
    - cron: '0 3 * * *'
  # 允许手动触发
  workflow_dispatch:
    inputs:
      category:
        description: '图片分类（可选）'
        required: false
        type: string
      count:
        description: '爬取图片数量'
        required: false
        default: '3'
        type: string

jobs:
  crawl-images:
    runs-on: ubuntu-latest
    # 添加权限
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 爬取图片（手动触发）
        if: github.event_name == 'workflow_dispatch'
        run: |
          python image_crawler.py --pexels-key ${{ secrets.PEXELS_API_KEY }} --count ${{ github.event.inputs.count }} --category "${{ github.event.inputs.category }}"
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}

      - name: 爬取图片（定时触发）
        if: github.event_name == 'schedule'
        run: |
          # 随机选择不同分类，每个分类爬取1张图片
          CATEGORIES=("风景" "城市" "动物" "建筑" "自然")
          for category in "${CATEGORIES[@]}"; do
            python image_crawler.py --pexels-key ${{ secrets.PEXELS_API_KEY }} --count 1 --category "$category"
            sleep 2
          done
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}

      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add images/ images.json
          git commit -m "自动爬取新图片 $(date +'%Y-%m-%d')" || echo "没有更改需要提交"
          git push
