name: 自动爬取图片

on:
  schedule:
    # 每天凌晨3点运行
    - cron: '0 3 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  crawl-images:
    runs-on: ubuntu-latest
    # 添加权限
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 爬取图片
        run: |
          python image_crawler.py --count 3

      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add images/ images.json
          git commit -m "自动爬取新图片 $(date +'%Y-%m-%d')" || echo "没有更改需要提交"
          git push
